# Training Curriculum 
# this yaml serves as container of the learning curriculum for the agent
# by determining the number of static/dynamic obstacles per stage
# (will carry on training on last stage when threshhold reached)


1:
  static: 2
  dynamic: 3
2:
  static: 4
  dynamic: 6
3:
  static: 6
  dynamic: 9
4:
  static: 8
  dynamic: 12
#1:
#  static: 0
#  dynamic: 0
#2:
#  static: 4
#  dynamic: 0
#3:
#  static: 8
#  dynamic: 0
#4:
#  static: 0
#  dynamic: 4
#5:
#  static: 4
#  dynamic: 4
#6:
#  static: 8
#  dynamic: 4
#7:
#  static: 0
#  dynamic: 8
#8:
#  static: 4
#  dynamic: 8
#9:
#  static: 8
#  dynamic: 8
#
# 1:
#   static: 0
#   dynamic: 0
# 2:
#   static: 0
#   dynamic: 4
# 3:
#   static: 0
#   dynamic: 8
# 4:
#   static: 0
#   dynamic: 12
# 5:
#   static: 0
#   dynamic: 16
# 6:
#   static: 0
#   dynamic: 20
# 7:
#   static: 0
#   dynamic: 24
# 8:
#   static: 2
#   dynamic: 28
# 9:
#   static: 2
#   dynamic: 32
# 10:
#   static: 2
#   dynamic: 40


